feat: add diff report path support

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,10 +23,18 @@ runs:
         set -o errexit
         set -o pipefail
         set -o nounset
-
+        TARGET_PATH="./target/sonar/report-task.txt"
+        DEFAULT_PATH=".scannerwork/report-task.txt"
+        REPORT_PATH=""
         # in newer versions of sonar scanner the default report-task.txt location may be different
-        REPORT_PATH=".scannerwork/report-task.txt"
-        REPORT_PATH="./target/sonar/report-task.txt"
+        if [ -f "$DEFAULT_PATH" ]; then
+            REPORT_PATH="$DEFAULT_PATH"
+        elif [ -f "$TARGET_PATH" ]; then
+            REPORT_PATH="$TARGET_PATH"
+        else
+          echo "No report path found!!"
+          exit 1
+        fi
         CE_TASK_ID_KEY="ceTaskId="
 
         SLEEP_TIME=5
@@ -40,7 +48,7 @@ runs:
         echo "QG Script --> Using task id of ${ce_task_id}"
 
         if [ -z "$ce_task_id" ]; then
-        echo "QG Script --> No task id found"
+          echo "QG Script --> No task id found"
         exit 1
         fi
 
@@ -56,17 +64,17 @@ runs:
         echo "QG Script --> Status of SonarQube task is ${ce_status}"
 
         if [ "${ce_status}" = "CANCELLED" ]; then
-        echo "QG Script --> SonarQube Compute job has been cancelled - exiting with error"
-        exit 1
+          echo "QG Script --> SonarQube Compute job has been cancelled - exiting with error"
+          exit 1
         fi
 
         if [ "${ce_status}" = "FAILED" ]; then
-        echo "QG Script --> SonarQube Compute job has failed - exiting with error"
-        exit 1
+          echo "QG Script --> SonarQube Compute job has failed - exiting with error"
+          exit 1
         fi
 
         if [ "${ce_status}" = "SUCCESS" ]; then
-        wait_for_success=false
+          wait_for_success=false
         fi
 
         sleep "${SLEEP_TIME}"
@@ -81,6 +89,6 @@ runs:
         echo "QG Script --> Quality Gate status is ${qg_status}"
 
         if [ "${qg_status}" != "OK" ]; then
-        echo "QG Script --> Quality gate is not OK - exiting with error"
-        exit 1
+          echo "QG Script --> Quality gate is not OK - exiting with error"
+          exit 1
         fi
